export const COUNTRY_CODE_LABELS: Record<string, string> = {
    AD: /* i18n */ 'Andorra',
    AE: /* i18n */ 'United Arab Emirates',
    AF: /* i18n */ 'Afghanistan',
    AG: /* i18n */ 'Antigua and Barbuda',
    AI: /* i18n */ 'Anguilla',
    AL: /* i18n */ 'Albania',
    AM: /* i18n */ 'Armenia',
    AO: /* i18n */ 'Angola',
    AQ: /* i18n */ 'Antarctica',
    AR: /* i18n */ 'Argentina',
    AS: /* i18n */ 'American Samoa',
    AT: /* i18n */ 'Austria',
    AU: /* i18n */ 'Australia',
    AW: /* i18n */ 'Aruba',
    AX: /* i18n */ 'Åland Islands',
    AZ: /* i18n */ 'Azerbaijan',
    BA: /* i18n */ 'Bosnia and Herzegovina',
    BB: /* i18n */ 'Barbados',
    BD: /* i18n */ 'Bangladesh',
    BE: /* i18n */ 'Belgium',
    BF: /* i18n */ 'Burkina Faso',
    BG: /* i18n */ 'Bulgaria',
    BH: /* i18n */ 'Bahrain',
    BI: /* i18n */ 'Burundi',
    BJ: /* i18n */ 'Benin',
    BL: /* i18n */ 'Saint Barthélemy',
    BM: /* i18n */ 'Bermuda',
    BN: /* i18n */ 'Brunei',
    BO: /* i18n */ 'Bolivia',
    BQ: /* i18n */ 'Caribbean Netherlands',
    BR: /* i18n */ 'Brazil',
    BS: /* i18n */ 'Bahamas',
    BT: /* i18n */ 'Bhutan',
    BV: /* i18n */ 'Bouvet Island',
    BW: /* i18n */ 'Botswana',
    BY: /* i18n */ 'Belarus',
    BZ: /* i18n */ 'Belize',
    CA: /* i18n */ 'Canada',
    CC: /* i18n */ 'Cocos Islands',
    CD: /* i18n */ 'Democratic Republic of the Congo',
    CF: /* i18n */ 'Central African Republic',
    CG: /* i18n */ 'Republic of the Congo',
    CH: /* i18n */ 'Switzerland',
    CI: /* i18n */ 'Ivory Coast',
    CK: /* i18n */ 'Cook Islands',
    CL: /* i18n */ 'Chile',
    CM: /* i18n */ 'Cameroon',
    CN: /* i18n */ 'China',
    CO: /* i18n */ 'Colombia',
    CR: /* i18n */ 'Costa Rica',
    CU: /* i18n */ 'Cuba',
    CV: /* i18n */ 'Cape Verde',
    CW: /* i18n */ 'Curaçao',
    CX: /* i18n */ 'Christmas Island',
    CY: /* i18n */ 'Cyprus',
    CZ: /* i18n */ 'Czech Republic',
    DE: /* i18n */ 'Germany',
    DJ: /* i18n */ 'Djibouti',
    DK: /* i18n */ 'Denmark',
    DM: /* i18n */ 'Dominica',
    DO: /* i18n */ 'Dominican Republic',
    DZ: /* i18n */ 'Algeria',
    EC: /* i18n */ 'Ecuador',
    EE: /* i18n */ 'Estonia',
    EG: /* i18n */ 'Egypt',
    EH: /* i18n */ 'Western Sahara',
    ER: /* i18n */ 'Eritrea',
    ES: /* i18n */ 'Spain',
    ET: /* i18n */ 'Ethiopia',
    FI: /* i18n */ 'Finland',
    FJ: /* i18n */ 'Fiji',
    FK: /* i18n */ 'Falkland Islands',
    FM: /* i18n */ 'Micronesia',
    FO: /* i18n */ 'Faroe Islands',
    FR: /* i18n */ 'France',
    GA: /* i18n */ 'Gabon',
    GB: /* i18n */ 'United Kingdom',
    GD: /* i18n */ 'Grenada',
    GE: /* i18n */ 'Georgia',
    GF: /* i18n */ 'French Guiana',
    GG: /* i18n */ 'Guernsey',
    GH: /* i18n */ 'Ghana',
    GI: /* i18n */ 'Gibraltar',
    GL: /* i18n */ 'Greenland',
    GM: /* i18n */ 'Gambia',
    GN: /* i18n */ 'Guinea',
    GP: /* i18n */ 'Guadeloupe',
    GQ: /* i18n */ 'Equatorial Guinea',
    GR: /* i18n */ 'Greece',
    GS: /* i18n */ 'South Georgia',
    GT: /* i18n */ 'Guatemala',
    GU: /* i18n */ 'Guam',
    GW: /* i18n */ 'Guinea-Bissau',
    GY: /* i18n */ 'Guyana',
    HK: /* i18n */ 'Hong Kong',
    HM: /* i18n */ 'Heard and McDonald Islands',
    HN: /* i18n */ 'Honduras',
    HR: /* i18n */ 'Croatia',
    HT: /* i18n */ 'Haiti',
    HU: /* i18n */ 'Hungary',
    ID: /* i18n */ 'Indonesia',
    IE: /* i18n */ 'Ireland',
    IL: /* i18n */ 'Israel',
    IM: /* i18n */ 'Isle of Man',
    IN: /* i18n */ 'India',
    IO: /* i18n */ 'British Indian Ocean Territory',
    IQ: /* i18n */ 'Iraq',
    IR: /* i18n */ 'Iran',
    IS: /* i18n */ 'Iceland',
    IT: /* i18n */ 'Italy',
    JE: /* i18n */ 'Jersey',
    JM: /* i18n */ 'Jamaica',
    JO: /* i18n */ 'Jordan',
    JP: /* i18n */ 'Japan',
    KE: /* i18n */ 'Kenya',
    KG: /* i18n */ 'Kyrgyzstan',
    KH: /* i18n */ 'Cambodia',
    KI: /* i18n */ 'Kiribati',
    KM: /* i18n */ 'Comoros',
    KN: /* i18n */ 'Saint Kitts and Nevis',
    KP: /* i18n */ 'North Korea',
    KR: /* i18n */ 'South Korea',
    KW: /* i18n */ 'Kuwait',
    KY: /* i18n */ 'Cayman Islands',
    KZ: /* i18n */ 'Kazakhstan',
    LA: /* i18n */ 'Laos',
    LB: /* i18n */ 'Lebanon',
    LC: /* i18n */ 'Saint Lucia',
    LI: /* i18n */ 'Liechtenstein',
    LK: /* i18n */ 'Sri Lanka',
    LR: /* i18n */ 'Liberia',
    LS: /* i18n */ 'Lesotho',
    LT: /* i18n */ 'Lithuania',
    LU: /* i18n */ 'Luxembourg',
    LV: /* i18n */ 'Latvia',
    LY: /* i18n */ 'Libya',
    MA: /* i18n */ 'Morocco',
    MC: /* i18n */ 'Monaco',
    MD: /* i18n */ 'Moldova',
    ME: /* i18n */ 'Montenegro',
    MF: /* i18n */ 'Saint Martin',
    MG: /* i18n */ 'Madagascar',
    MH: /* i18n */ 'Marshall Islands',
    MK: /* i18n */ 'North Macedonia',
    ML: /* i18n */ 'Mali',
    MM: /* i18n */ 'Myanmar',
    MN: /* i18n */ 'Mongolia',
    MO: /* i18n */ 'Macau',
    MP: /* i18n */ 'Northern Mariana Islands',
    MQ: /* i18n */ 'Martinique',
    MR: /* i18n */ 'Mauritania',
    MS: /* i18n */ 'Montserrat',
    MT: /* i18n */ 'Malta',
    MU: /* i18n */ 'Mauritius',
    MV: /* i18n */ 'Maldives',
    MW: /* i18n */ 'Malawi',
    MX: /* i18n */ 'Mexico',
    MY: /* i18n */ 'Malaysia',
    MZ: /* i18n */ 'Mozambique',
    NA: /* i18n */ 'Namibia',
    NC: /* i18n */ 'New Caledonia',
    NE: /* i18n */ 'Niger',
    NF: /* i18n */ 'Norfolk Island',
    NG: /* i18n */ 'Nigeria',
    NI: /* i18n */ 'Nicaragua',
    NL: /* i18n */ 'Netherlands',
    NO: /* i18n */ 'Norway',
    NP: /* i18n */ 'Nepal',
    NR: /* i18n */ 'Nauru',
    NU: /* i18n */ 'Niue',
    NZ: /* i18n */ 'New Zealand',
    OM: /* i18n */ 'Oman',
    PA: /* i18n */ 'Panama',
    PE: /* i18n */ 'Peru',
    PF: /* i18n */ 'French Polynesia',
    PG: /* i18n */ 'Papua New Guinea',
    PH: /* i18n */ 'Philippines',
    PK: /* i18n */ 'Pakistan',
    PL: /* i18n */ 'Poland',
    PM: /* i18n */ 'Saint Pierre and Miquelon',
    PN: /* i18n */ 'Pitcairn Islands',
    PR: /* i18n */ 'Puerto Rico',
    PS: /* i18n */ 'Palestine',
    PT: /* i18n */ 'Portugal',
    PW: /* i18n */ 'Palau',
    PY: /* i18n */ 'Paraguay',
    QA: /* i18n */ 'Qatar',
    RE: /* i18n */ 'Réunion',
    RO: /* i18n */ 'Romania',
    RS: /* i18n */ 'Serbia',
    RU: /* i18n */ 'Russia',
    RW: /* i18n */ 'Rwanda',
    SA: /* i18n */ 'Saudi Arabia',
    SB: /* i18n */ 'Solomon Islands',
    SC: /* i18n */ 'Seychelles',
    SD: /* i18n */ 'Sudan',
    SE: /* i18n */ 'Sweden',
    SG: /* i18n */ 'Singapore',
    SH: /* i18n */ 'Saint Helena',
    SI: /* i18n */ 'Slovenia',
    SJ: /* i18n */ 'Svalbard and Jan Mayen',
    SK: /* i18n */ 'Slovakia',
    SL: /* i18n */ 'Sierra Leone',
    SM: /* i18n */ 'San Marino',
    SN: /* i18n */ 'Senegal',
    SO: /* i18n */ 'Somalia',
    SR: /* i18n */ 'Suriname',
    SS: /* i18n */ 'South Sudan',
    ST: /* i18n */ 'São Tomé and Príncipe',
    SV: /* i18n */ 'El Salvador',
    SX: /* i18n */ 'Sint Maarten',
    SY: /* i18n */ 'Syria',
    SZ: /* i18n */ 'Eswatini',
    TC: /* i18n */ 'Turks and Caicos Islands',
    TD: /* i18n */ 'Chad',
    TF: /* i18n */ 'French Southern Territories',
    TG: /* i18n */ 'Togo',
    TH: /* i18n */ 'Thailand',
    TJ: /* i18n */ 'Tajikistan',
    TK: /* i18n */ 'Tokelau',
    TL: /* i18n */ 'Timor-Leste',
    TM: /* i18n */ 'Turkmenistan',
    TN: /* i18n */ 'Tunisia',
    TO: /* i18n */ 'Tonga',
    TR: /* i18n */ 'Turkey',
    TT: /* i18n */ 'Trinidad and Tobago',
    TV: /* i18n */ 'Tuvalu',
    TW: /* i18n */ 'Taiwan',
    TZ: /* i18n */ 'Tanzania',
    UA: /* i18n */ 'Ukraine',
    UG: /* i18n */ 'Uganda',
    UM: /* i18n */ 'United States Minor Outlying Islands',
    US: /* i18n */ 'United States',
    UY: /* i18n */ 'Uruguay',
    UZ: /* i18n */ 'Uzbekistan',
    VA: /* i18n */ 'Vatican City',
    VC: /* i18n */ 'Saint Vincent and the Grenadines',
    VE: /* i18n */ 'Venezuela',
    VG: /* i18n */ 'British Virgin Islands',
    VI: /* i18n */ 'U.S. Virgin Islands',
    VN: /* i18n */ 'Vietnam',
    VU: /* i18n */ 'Vanuatu',
    WF: /* i18n */ 'Wallis and Futuna',
    WS: /* i18n */ 'Samoa',
    YE: /* i18n */ 'Yemen',
    YT: /* i18n */ 'Mayotte',
    ZA: /* i18n */ 'South Africa',
    ZM: /* i18n */ 'Zambia',
    ZW: /* i18n */ 'Zimbabwe'
};
